blueprint:
  name: Low Battery Notifications
  description: "# Low Battery Notifications\n\nAutomation for notifying a given device when a sensor battery is below the specified threshold, with support for excluding integrations, devices, and entities."
  domain: automation
  input:
    time:
      name: '[REQUIRED] Trigger Time'
      description: The time you would like the automation to notify you of any low batteries.
      default: '00:00:00'
      selector:
        time:

    notify_devices:
      name: '[REQUIRED] Notification Devices'
      description: Devices to notify when a low battery alert is triggered.
      selector:
        device:
          multiple: true
          filter:
            integration: mobile_app

    low_battery_threshold:
      name: '[OPTIONAL] Low Battery Threshold'
      description: Sensors with battery levels below this threshold will be considered low.
      default: 10
      selector:
        number:
          min: 0
          max: 100
          step: 1
          unit_of_measurement: '%'
          mode: slider

    exclude_devices:
      name: '[OPTIONAL] Exclude Devices'
      description: Devices to exclude from low battery detection.
      default: []
      selector:
        device:
          multiple: true
          entity:
            domain: sensor
            device_class: battery

    detect_battery_binary_sensors:
      name: '[OPTIONAL] Detect Battery Binary Sensors'
      description: Alert when binary sensors with a `device_class` of `battery` are in state `on`.
      default: true
      selector:
        boolean:

variables:
  exclude_devices: !input exclude_devices
  low_battery_threshold: !input low_battery_threshold
  detect_battery_binary_sensors: !input detect_battery_binary_sensors

trigger:
  - platform: time
    at: !input time

action:
  - alias: Set variables
    variables:
      sensors: >-
        {% set low_battery = namespace(entities=[]) -%}
        {% for state in states.sensor -%}
          {% if device_attr(state.entity_id, 'id') not in exclude_devices
                 and state_attr(state.entity_id, 'device_class') == 'battery'
                 and state.state not in ['unknown', 'unavailable']
                 and state.state | float(-1) != -1 -%}
            {% if state.state | float <= low_battery_threshold -%}
              {% set low_battery.entities = low_battery.entities + [state.name ~ ' (' ~ state.state ~ '%)'] -%}
            {% endif -%}
          {% endif -%}
        {%- endfor -%}
        {% if detect_battery_binary_sensors -%}
          {% for state in states.binary_sensor -%}
            {% if state_attr(state.entity_id, 'device_class') == 'battery'
                  and state.state == 'on' -%}
              {% set low_battery.entities = low_battery.entities + [state.name] -%}
            {% endif -%}
          {% endfor -%}
        {% endif -%}
        {{ low_battery.entities | sort | join('\n') }}

  - alias: Notify if there are any devices with low battery
    if:
      - condition: template
        value_template: "{{ sensors | length > 0 }}"
    then:
      - alias: Notify
        repeat:
          for_each: !input notify_devices
          sequence:
            - alias: Notify
              service: notify.mobile_app_{{ device_attr(repeat.item, 'name') | slugify }}
              data:
                title: Low Battery Alert
                message: "{{ sensors }}"
mode: single
